/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author JUAN DAVID SEPULVEDA
 */
public class NuevoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form NuevoUsuario1
     */
    public NuevoUsuario() {
        initComponents();
    }

    public JButton getBtnGuardarNuevo() {
        return BtnGuardarNuevo;
    }

    public void setBtnGuardarNuevo(JButton BtnGuardarNuevo) {
        this.BtnGuardarNuevo = BtnGuardarNuevo;
    }

    public JButton getBtnCancelarNuevo() {
        return BtnCancelarNuevo;
    }

    public void setBtnCancelarNuevo(JButton BtnCancelar) {
        this.BtnCancelarNuevo = BtnCancelar;
    }

    public JComboBox<String> getCbxCargo() {
        return cbxCargo;
    }

    public JButton getBTnGuardarNuevo() {
        return BtnGuardarNuevo;
    }

    public void setBTnGuardarNuevo(JButton BTnGuardarNuevo) {
        this.BtnGuardarNuevo = BTnGuardarNuevo;
    }

    public JButton getBtnMostrarClaveNuevo() {
        return BtnMostrarClaveNuevo;
    }

    public void setBtnMostrarClaveNuevo(JButton BtnMostrarClaveNuevo) {
        this.BtnMostrarClaveNuevo = BtnMostrarClaveNuevo;
    }

    public JPanel getjPanelNuevoUsuario() {
        return jPanelNuevoUsuario;
    }

    public void setjPanelNuevoUsuario(JPanel jPanelNuevoUsuario) {
        this.jPanelNuevoUsuario = jPanelNuevoUsuario;
    }

    public void setCbxCargo(JComboBox<String> cbxCargo) {
        this.cbxCargo = cbxCargo;
    }

    public JComboBox<String> getCbxSexo() {
        return cbxSexo;
    }

    public void setCbxSexo(JComboBox<String> cbxSexo) {
        this.cbxSexo = cbxSexo;
    }

    public JComboBox<String> getCbxTipoDocumento() {
        return cbxTipoDocumento;
    }

    public void setCbxTipoDocumento(JComboBox<String> cbxTipoDocumento) {
        this.cbxTipoDocumento = cbxTipoDocumento;
    }

    public JPanel getjPanelUsuario() {
        return jPanelNuevoUsuario;
    }

    public void setjPanelUsuario(JPanel jPanelUsuario) {
        this.jPanelNuevoUsuario = jPanelUsuario;
    }

    public JPasswordField getjPassClave() {
        return jPassClave;
    }

    public void setjPassClave(JPasswordField jPassClave) {
        this.jPassClave = jPassClave;
    }

    public JTextField getjTexCorreo() {
        return jTexCorreo;
    }

    public JDateChooser getJdchFecha() {
        return JdchFecha;
    }

    public void setJdchFecha(JDateChooser jdchFecha) {
        this.JdchFecha = jdchFecha;
    }

    public void setjTexCorreo(JTextField jTexCorreo) {
        this.jTexCorreo = jTexCorreo;
    }

    public JTextField getjTexDireccion() {
        return jTexDireccion;
    }

    public void setjTexDireccion(JTextField jTexDireccion) {
        this.jTexDireccion = jTexDireccion;
    }

    public JTextField getjTexDocumento() {
        return jTexDocumento;
    }

    public void setjTexDocumento(JTextField jTexDocumento) {
        this.jTexDocumento = jTexDocumento;
    }

    public JTextField getjTexLogin() {
        return jTexLogin;
    }

    public void setjTexLogin(JTextField jTexLogin) {
        this.jTexLogin = jTexLogin;
    }

    public JTextField getjTexNombre() {
        return jTexNombre;
    }

    public void setjTexNombre(JTextField jTexNombre) {
        this.jTexNombre = jTexNombre;
    }

    public JTextField getjTexTelefono() {
        return jTexTelefono;
    }

    public void setjTexTelefono(JTextField jTexTelefono) {
        this.jTexTelefono = jTexTelefono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNuevoUsuario = new javax.swing.JPanel();
        jLbNuevoUsuario = new javax.swing.JLabel();
        jLbDocumento = new javax.swing.JLabel();
        jTexDocumento = new javax.swing.JTextField();
        jLbNombre = new javax.swing.JLabel();
        jTexNombre = new javax.swing.JTextField();
        jLbCorreo = new javax.swing.JLabel();
        jTexCorreo = new javax.swing.JTextField();
        jLbDireccion = new javax.swing.JLabel();
        jTexDireccion = new javax.swing.JTextField();
        jLbSexo = new javax.swing.JLabel();
        cbxSexo = new javax.swing.JComboBox<>();
        jLabelTelefono = new javax.swing.JLabel();
        jTexTelefono = new javax.swing.JTextField();
        jLbFecha_de_Nacimiento = new javax.swing.JLabel();
        JdchFecha = new com.toedter.calendar.JDateChooser();
        cbxCargo = new javax.swing.JComboBox<>();
        jLbCargo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTexLogin = new javax.swing.JTextField();
        jLbel9 = new javax.swing.JLabel();
        jPassClave = new javax.swing.JPasswordField();
        BtnCancelarNuevo = new javax.swing.JButton();
        BtnGuardarNuevo = new javax.swing.JButton();
        jLabelTipo = new javax.swing.JLabel();
        cbxTipoDocumento = new javax.swing.JComboBox<>();
        BtnMostrarClaveNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jPanelNuevoUsuario.setBackground(new java.awt.Color(204, 204, 204));
        jPanelNuevoUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        jPanelNuevoUsuario.setForeground(new java.awt.Color(255, 0, 0));

        jLbNuevoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jLbNuevoUsuario.setForeground(new java.awt.Color(255, 0, 0));
        jLbNuevoUsuario.setText("NUEVO USUARIO");

        jLbDocumento.setForeground(new java.awt.Color(255, 0, 0));
        jLbDocumento.setText("Documento");

        jTexDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexDocumentoActionPerformed(evt);
            }
        });

        jLbNombre.setForeground(new java.awt.Color(255, 0, 0));
        jLbNombre.setText("Nombre");

        jLbCorreo.setForeground(new java.awt.Color(255, 0, 0));
        jLbCorreo.setText("Correo");

        jLbDireccion.setForeground(new java.awt.Color(255, 0, 0));
        jLbDireccion.setText("Direccion");

        jLbSexo.setForeground(new java.awt.Color(255, 0, 0));
        jLbSexo.setText("Sexo");

        cbxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSexoActionPerformed(evt);
            }
        });

        jLabelTelefono.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTelefono.setText("Telefono");

        jLbFecha_de_Nacimiento.setForeground(new java.awt.Color(255, 0, 0));
        jLbFecha_de_Nacimiento.setText("<html>Fecha de Nacimiento<html>");

        JdchFecha.setDateFormatString("yyyy-MM-dd");

        jLbCargo.setForeground(new java.awt.Color(255, 0, 0));
        jLbCargo.setText("Cargo");

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Login");

        jLbel9.setForeground(new java.awt.Color(255, 0, 0));
        jLbel9.setText("Clave");

        BtnCancelarNuevo.setForeground(new java.awt.Color(255, 0, 0));
        BtnCancelarNuevo.setText("Cancelar");

        BtnGuardarNuevo.setForeground(new java.awt.Color(255, 0, 0));
        BtnGuardarNuevo.setText("Guardar");
        BtnGuardarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarNuevoActionPerformed(evt);
            }
        });

        jLabelTipo.setBackground(new java.awt.Color(255, 0, 0));
        jLabelTipo.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTipo.setText("Tipo Documento");

        cbxTipoDocumento.setBackground(new java.awt.Color(255, 255, 255));
        cbxTipoDocumento.setForeground(new java.awt.Color(255, 0, 0));
        cbxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Tipo de Documento", "Cedula", "Tarjeta_Identidad", "Registro" }));
        cbxTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoDocumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNuevoUsuarioLayout = new javax.swing.GroupLayout(jPanelNuevoUsuario);
        jPanelNuevoUsuario.setLayout(jPanelNuevoUsuarioLayout);
        jPanelNuevoUsuarioLayout.setHorizontalGroup(
            jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                        .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLbFecha_de_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(jLbDocumento)
                                .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLbCorreo)
                                    .addComponent(jLbNombre)))
                            .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                                .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLbSexo)
                                    .addComponent(jLbDireccion))
                                .addGap(29, 29, 29)))
                        .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTexDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTexCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTexNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jTexDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                                .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(JdchFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNuevoUsuarioLayout.createSequentialGroup()
                                        .addComponent(BtnCancelarNuevo)
                                        .addGap(28, 28, 28)))
                                .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLbCargo)
                                    .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                                        .addComponent(jLabelTelefono)
                                        .addGap(52, 52, 52)
                                        .addComponent(jTexTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(BtnGuardarNuevo))))
                            .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                                .addComponent(jTexLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLbel9)
                                .addGap(39, 39, 39)
                                .addComponent(jPassClave, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnMostrarClaveNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabelTipo)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLbNuevoUsuario)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelNuevoUsuarioLayout.setVerticalGroup(
            jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLbNuevoUsuario)
                .addGap(18, 18, 18)
                .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTipo)
                    .addComponent(cbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbDocumento)
                    .addComponent(jTexDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTexNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                        .addComponent(jLbCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                        .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLbDireccion)
                            .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                                .addComponent(jTexCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jTexDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
                            .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLbSexo)
                                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)))
                        .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                                .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLbFecha_de_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTexTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTelefono))
                                .addGap(35, 192, Short.MAX_VALUE))
                            .addGroup(jPanelNuevoUsuarioLayout.createSequentialGroup()
                                .addComponent(JdchFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnMostrarClaveNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jPassClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLbel9)
                                        .addComponent(jTexLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)))
                                .addGap(44, 44, 44)
                                .addGroup(jPanelNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnCancelarNuevo)
                                    .addComponent(BtnGuardarNuevo))
                                .addGap(24, 24, 24))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarNuevoActionPerformed

    }//GEN-LAST:event_BtnGuardarNuevoActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void cbxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSexoActionPerformed

    private void cbxTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoDocumentoActionPerformed

    private void jTexDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexDocumentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelarNuevo;
    private javax.swing.JButton BtnGuardarNuevo;
    private javax.swing.JButton BtnMostrarClaveNuevo;
    private com.toedter.calendar.JDateChooser JdchFecha;
    private javax.swing.JComboBox<String> cbxCargo;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JComboBox<String> cbxTipoDocumento;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLbCargo;
    private javax.swing.JLabel jLbCorreo;
    private javax.swing.JLabel jLbDireccion;
    private javax.swing.JLabel jLbDocumento;
    private javax.swing.JLabel jLbFecha_de_Nacimiento;
    private javax.swing.JLabel jLbNombre;
    private javax.swing.JLabel jLbNuevoUsuario;
    private javax.swing.JLabel jLbSexo;
    private javax.swing.JLabel jLbel9;
    private javax.swing.JPanel jPanelNuevoUsuario;
    private javax.swing.JPasswordField jPassClave;
    private javax.swing.JTextField jTexCorreo;
    private javax.swing.JTextField jTexDireccion;
    private javax.swing.JTextField jTexDocumento;
    private javax.swing.JTextField jTexLogin;
    private javax.swing.JTextField jTexNombre;
    private javax.swing.JTextField jTexTelefono;
    // End of variables declaration//GEN-END:variables

}
