/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author JUAN DAVID SEPULVEDA
 */
public class NuevoProducto extends javax.swing.JFrame {

    /**
     * Creates new form NuevoProducto
     */
    public NuevoProducto() {
        initComponents();
    }

    public JButton getBtnBuscarImagen() {
        return BtnBuscarImagen;
    }

    public void setBtnBuscarImagen(JButton BtnBuscarImagen) {
        this.BtnBuscarImagen = BtnBuscarImagen;
    }

    public JButton getBtnCancelar() {
        return BtnCancelar;
    }

    public void setBtnCancelar(JButton BtnCancelar) {
        this.BtnCancelar = BtnCancelar;
    }

    public JButton getBtnGuardarProducto() {
        return BtnGuardarProducto;
    }

    public void setBtnGuardarProducto(JButton BtnGuardarProducto) {
        this.BtnGuardarProducto = BtnGuardarProducto;
    }

    public JTextArea getjTexAreaDesProducto() {
        return jTexAreaDesProducto;
    }

    public void setjTexAreaDesProducto(JTextArea jTexAreaDesProducto) {
        this.jTexAreaDesProducto = jTexAreaDesProducto;
    }

    public JTextField getjTexNombreProducto() {
        return jTexNombreProducto;
    }

    public void setjTexNombreProducto(JTextField jTexNombreProducto) {
        this.jTexNombreProducto = jTexNombreProducto;
    }

    public JTextField getjTexImagenProducto() {
        return jTexImagenProducto;
    }

    public void setjTexImagenProducto(JTextField jTexImagenProducto) {
        this.jTexImagenProducto = jTexImagenProducto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProducto = new javax.swing.JPanel();
        jLabelNuevoProducto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTexNombreProducto = new javax.swing.JTextField();
        jTexImagenProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTexAreaDesProducto = new javax.swing.JTextArea();
        BtnGuardarProducto = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        BtnBuscarImagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNuevoProducto.setText("NUEVO PRODUCTO");

        jLabel1.setText("Nombre");

        jLabel2.setText("Imagen");

        jLabel3.setText("Descripcion");

        jTexAreaDesProducto.setColumns(20);
        jTexAreaDesProducto.setRows(5);
        jScrollPane1.setViewportView(jTexAreaDesProducto);

        BtnGuardarProducto.setText("Guardar");

        BtnCancelar.setText("Cancelar");

        BtnBuscarImagen.setText("Buscar Imagen");

        javax.swing.GroupLayout jPanelProductoLayout = new javax.swing.GroupLayout(jPanelProducto);
        jPanelProducto.setLayout(jPanelProductoLayout);
        jPanelProductoLayout.setHorizontalGroup(
            jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductoLayout.createSequentialGroup()
                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductoLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabelNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelProductoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelProductoLayout.createSequentialGroup()
                                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelProductoLayout.createSequentialGroup()
                                        .addComponent(BtnGuardarProducto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnCancelar))
                                    .addComponent(jTexImagenProducto)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addComponent(BtnBuscarImagen))
                            .addComponent(jTexNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanelProductoLayout.setVerticalGroup(
            jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTexNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTexImagenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnBuscarImagen)))
                .addGap(51, 51, 51)
                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardarProducto)
                    .addComponent(BtnCancelar))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarImagen;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnGuardarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNuevoProducto;
    private javax.swing.JPanel jPanelProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTexAreaDesProducto;
    private javax.swing.JTextField jTexImagenProducto;
    private javax.swing.JTextField jTexNombreProducto;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonBuscarImagen() {
        return BtnBuscarImagen;
    }

    public void setjButtonBuscarImagen(JButton jButtonBuscarImagen) {
        this.BtnBuscarImagen = jButtonBuscarImagen;
    }

    public JButton getjButtonCancelar() {
        return BtnCancelar;
    }

    public void setjButtonCancelar(JButton jButtonCancelar) {
        this.BtnCancelar = jButtonCancelar;
    }

    public JButton getjButtonGuardar() {
        return BtnGuardarProducto;
    }

    public void setjButtonGuardar(JButton jButtonGuardar) {
        this.BtnGuardarProducto = jButtonGuardar;
    }

    public JLabel getjLabelNuevoProducto() {
        return jLabelNuevoProducto;
    }

    public void setjLabelNuevoProducto(JLabel jLabelNuevoProducto) {
        this.jLabelNuevoProducto = jLabelNuevoProducto;
    }

    public JPanel getjPanelProducto() {
        return jPanelProducto;
    }

    public void setjPanelProducto(JPanel jPanelProducto) {
        this.jPanelProducto = jPanelProducto;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextField getjTexImagen() {
        return jTexImagenProducto;
    }

    public void setjTexImagen(JTextField jTexImagen) {
        this.jTexImagenProducto = jTexImagen;
    }

    public JTextField getjTexNombre() {
        return jTexNombreProducto;
    }

    public void setjTexNombre(JTextField jTexNombre) {
        this.jTexNombreProducto = jTexNombre;
    }

    public JTextArea getjTextAreaDescripcion() {
        return jTexAreaDesProducto;
    }

    public void setjTextAreaDescripcion(JTextArea jTextAreaDescripcion) {
        this.jTexAreaDesProducto = jTextAreaDescripcion;
    }

}
